server:
  port: 9098
spring:
  application:
    name : student-service
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      register: true

management:
  security:
    enabled: false