logging:
  level:
    com:
      cursosdedesarrollo:
        eurekaclient:
          ItemClient: DEBUG
ribbon:
  products:
    listOfServers: localhost
eureka:
  client:
    fetch-registry: true
  enabled: false
feign:
  hystrix:
    enabled: true
server:
  port: 8089
spring:
  application:
    name: edge-service
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream