eureka:
  client:
    fetch-registry: true
    enabled: true
feign:
  hystrix:
    enabled: true
server:
  port: 8089
spring:
  application:
    name: edge-service
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream