spring:
  application:
    name: HelloClient

server:
  port: 7211

eureka:
  password: password
  client:
    # URL del servidor eureka
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
    # Es necesario para que vea las instancias de app
    fetchRegistry: true
    instance:
      leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}


